service: kotlin-simple

provider:
  name: aws
  runtime: java8

package:
  artifact: ${file(build/build.json):distribution}

functions:
  hello:
    handler: com.serverless.Handler

plugins:
  - serverless-jvm-plugin
