service: aws-clojure

provider:
  name: aws
  runtime: java8
  timeout: 300
  memorySize: 1536
  logRetentionInDays: 30

package:
  artifact: ${file(build/build.json):distribution}

functions:
  hello:
    handler: hello::handler
    tags:
      VERSION: ${file(build/build.json):version}
