service: java-simple

provider:
  name: aws
  runtime: java8

package:
  artifact: build/libs/java-simple-all.jar

functions:
  hello:
    handler: com.serverless.handler.Hello::handleRequest
    events:
      - http:
          path: /hello
          method: get

